version: "3.8"

services:
  app:
    build:
      context: ./sistema-entregas-api
      dockerfile: Dockerfile
    image: unicad-sistemas-entrega
    container_name: unicad-sistemas-entrega
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - unicad-network
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate dev && npm run dev"

  web:
    build:
      context: ./sistema-entregas-frontend
      dockerfile: Dockerfile
    container_name: web-app
    networks:
      - unicad-network
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - unicad-network
    depends_on:
      - web
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - unicad-network
    env_file:
      - .env

volumes:
  postgres-data:

networks:
  unicad-network:
    driver: bridge
