services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: unicad-sistemas-entrega
    container_name: unicad-sistemas-entrega
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - unicad-network
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate dev && npm run dev"

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - unicad-network
    env_file:
      - .env

volumes:
  postgres-data:

networks:
  unicad-network:
    driver: bridge
